In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
 ##sentences
 sent=[ 'The glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'understand the meaning of words',
        'your videos are good',]

In [ ]:
sent

['The glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
###Define the vocabulary size
voc_size = 10000

In [ ]:
sent

['The glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
##One hot Representation
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3993, 1525, 617, 7673],
 [3993, 1525, 617, 459],
 [3993, 2522, 617, 4576],
 [5857, 45, 2237, 3059, 8807],
 [3146, 3993, 2133, 617, 7697],
 [5350, 9998, 6665, 3059]]

In [ ]:
## word embedding representation

In [ ]:
from tensorflow.keras.layers import Embedding
##from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length = 8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3993 1525  617 7673]
 [   0    0    0    0 3993 1525  617  459]
 [   0    0    0    0 3993 2522  617 4576]
 [   0    0    0 5857   45 2237 3059 8807]
 [   0    0    0 3146 3993 2133  617 7697]
 [   0    0    0    0 5350 9998 6665 3059]]


In [ ]:
## feature representation
dim = 10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Piyush\miniconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.build(input_shape=(None, sent_length))


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[[ 2.50673406e-02,  2.25762762e-02, -6.64743036e-03,
         -1.09947845e-03, -1.88583378e-02,  3.72090451e-02,
         -9.62332636e-03,  4.42624092e-04, -8.42738897e-04,
         -5.31570986e-03],
        [ 2.50673406e-02,  2.25762762e-02, -6.64743036e-03,
         -1.09947845e-03, -1.88583378e-02,  3.72090451e-02,
         -9.62332636e-03,  4.42624092e-04, -8.42738897e-04,
         -5.31570986e-03],
        [ 2.50673406e-02,  2.25762762e-02, -6.64743036e-03,
         -1.09947845e-03, -1.88583378e-02,  3.72090451e-02,
         -9.62332636e-03,  4.42624092e-04, -8.42738897e-04,
         -5.31570986e-03],
        [ 2.50673406e-02,  2.25762762e-02, -6.64743036e-03,
         -1.09947845e-03, -1.88583378e-02,  3.72090451e-02,
         -9.62332636e-03,  4.42624092e-04, -8.42738897e-04,
         -5.31570986e-03],
        [-4.06460762e-02, -6.37257099e-03,  1.32776424e-03,
         -4.06007543e-02,  4.63177897e-02,  1.19037256e-02,
         -4.65833209e-02, -1.30075924e-02,  1.829955

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 3993, 1525,  617, 7673])